name: Send a Tweet
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1.0.0
        with:
          status: ${{ github.event.head_commit.message }}, Visit govdashboard.ie for more info.
          consumer-key: ${{ secrets.CONSUMER_KEY }}
          consumer-secret: ${{ secrets.CONSUMER_SECRET }}
          access-token: ${{ secrets.ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}